export const REFRESH = 'REFRESH'
export const FETCH_NEWS = 'FETCH_NEWS'
export const LOAD_MORE = 'LOAD_MORE'
export const GET_INTO_DETAILS = 'GET_INTO_DETAILS'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_SIGNUP = 'USER_SIGNUP'
